services:
  romm-server:
    image: rommapp/romm:latest
    container_name: romm_server
    restart: unless-stopped
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    environment:
      - DB_HOST=romm-db
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWORD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - SCREENSCRAPER_USER=${ROMM_SCREENSCRAPER_USER}
      - SCREENSCRAPER_PASSWORD=${ROMM_SCREENSCRAPER_PASSWORD}
      - RETROACHIEVEMENTS_API_KEY=${ROMM_RETROACHIEVEMENTS_API_KEY}
      - REFRESH_RETROACHIEVEMENTS_CACHE_DAYS=${ROMM_REFRESH_RETROACHIEVEMENTS_CACHE_DAYS}
      - STEAMGRIDDB_API_KEY=${ROMM_STEAMGRIDDB_API_KEY}
      - HASHEOUS_API_ENABLED=${ROMM_HASHEOUS_API_ENABLED}
      - OIDC_ENABLED=${ROMM_OIDC_ENABLED}
      - OIDC_PROVIDER=${ROMM_OIDC_PROVIDER}
      - OIDC_CLIENT_ID=${ROMM_OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${ROMM_OIDC_CLIENT_SECRET}
      - OIDC_REDIRECT_URI=${ROMM_OIDC_REDIRECT_URI}
      - OIDC_SERVER_APPLICATION_URL=${ROMM_OIDC_SERVER_APPLICATION_URL}
    volumes:
      - ${ROMM_RESOURCES_LOCATION}:/romm/resources
      - ${ROMM_REDIS_DATA_LOCATION}:/redis-data
      - ${ROMM_LIBRARY_LOCATION}:/romm/library
      - ${ROMM_ASSETS_LOCATION}:/romm/assets
      - ${ROMM_CONFIG_LOCATION}:/romm/config
    networks:
      - romm-network
      - proxy-bridge

  romm-db:
    image: mariadb:latest
    container_name: romm_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_LOCATION}:/var/lib/mysql
    networks:
      - romm-network

networks:
  romm-network:
    name: romm_default

  proxy-bridge:
    name: proxy_bridge
    external: true
